Try various things

diff --git a/.github/workflows/pr-comment.yml b/.github/workflows/pr-comment.yml
--- a/.github/workflows/pr-comment.yml
+++ b/.github/workflows/pr-comment.yml
@@ -13,27 +13,35 @@ jobs:
     steps:
     - name: Checkout repo
       uses: actions/checkout@v2.3.1
-      # with:
-      #   # For an on-PR workflow, it would normally checkout a merge commit of the PR branch
-      #   # into the base branch. Instead we want the tip of the PR branch:
-      #   ref: ${{ github.head_ref }}
 
-    # - name: Configure git
-    #   run: |
-    #     git config --global user.name "github-actions[bot]"
-    #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+    - name: Export $ASDF
+      run: |
+        ASDF=34
+        echo "::set-env name=ASDF::$ASDF"
+        echo "$ASDF"
 
     - name: Deliberately fail workflow
-      run: exit 1
+      run: |
+        msg="Foo bar
+          baz"
+        echo "::warning ::$msg"
+        echo "Open the pod bay doors, Hal."
+        echo "::error ::I'm sorry, Dave. I'm afraid I can't do that."
+        exit 1
 
     - name: Comment on PR
       if: always()
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        WORKFLOW: ${{ github.workflow }}
+        HEAD_REF: ${{ github.head_ref }}
       run: |
-        comment_json=$( node .github/pr-comment.js "${{ github.workflow }}" "${{ github.head_ref }}" )
+        echo "That env var from prev step: $ASDF"
+
+        comment_json=$( node .github/pr-comment.js )
+
         curl -X POST \
           ${{ github.event.pull_request.comments_url }} \
-          -H "authorization: Bearer ${GH_TOKEN}" \
           -H "content-type: application/json" \
-          --data "$comment_json"
+          --data "$comment_json" \
+          --fail
