Trying more stuff

diff --git a/.github/workflows/pr-comment.yml b/.github/workflows/pr-comment.yml
--- a/.github/workflows/pr-comment.yml
+++ b/.github/workflows/pr-comment.yml
@@ -11,7 +11,7 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 5
     env:
-      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      REPOSITORY: ${{ github.repository }}
     steps:
     - name: Checkout repo
       uses: actions/checkout@v2.3.1
@@ -24,11 +24,15 @@ jobs:
 
     - name: Check milestone
       shell: node {0}
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         const {exec} = require('child_process');
         const env = process.env;
-        const request = `curl https://api.github.com/repos/${{ github.repository }}/milestones \
-          -H "authorization: Bearer ${env.GH_TOKEN}" \
+        const setEnv = (name, value) => { console.log(`::set-env name=${name}::${value}`) };
+
+        const request = `curl https://api.github.com/repos/${env.REPOSITORY}/milestones \
+          -H "authorization: Bearer $GH_TOKEN" \
           --silent --fail`;
         exec(request, (err, stdout, stderr) => {
           if (err) throw err;
@@ -36,12 +40,14 @@ jobs:
           const response_arr = JSON.parse(stdout);
           for (const milestone of response_arr) {
             if (milestone.title.includes(env.ASDF)) {
-              console.log(`::set-env name=MILESTONE_OPEN_ISSUES::${milestone.open_issues}`);
+              setEnv("MILESTONE_NUMBER", milestone.number);
+              setEnv("MILESTONE_TITLE", milestone.title);
+              setEnv("MILESTONE_OPEN_ISSUES", milestone.open_issues);
               return;
             }
           }
           console.log(response_arr);
-          throw `Could not find milestone matching '${env.ASDF}'`;
+          throw `::error :: Could not find milestone matching '${env.ASDF}'`;
         });
 
     - run: echo "$MILESTONE_OPEN_ISSUES"
@@ -61,16 +67,22 @@ jobs:
     # })();"
 
 
-    # - name: Comment on PR
-    #   if: always()
-    #     WORKFLOW: ${{ github.workflow }}
-    #     HEAD_REF: ${{ github.head_ref }}
-    #   run: |
-    #     comment_json=$( node .github/pr-comment.js )
+    # - name: Deliberately fail
+    #   run: exit 1
 
-    #     curl -X POST \
-    #       ${{ github.event.pull_request.comments_url }} \
-    #       -H "content-type: application/json" \
-    #       -H "authorization: Bearer ${GH_TOKEN}" \
-    #       --data "$comment_json" \
-    #       --fail
+    - name: Comment on PR
+      if: always()
+      env:
+        WORKFLOW: ${{ github.workflow }}
+        HEAD_REF: ${{ github.head_ref }}
+        JOB_STATUS: ${{ job.status }}
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        comment_json=$( node .github/pr-comment.js )
+
+        curl -X POST \
+          ${{ github.event.pull_request.comments_url }} \
+          -H "content-type: application/json" \
+          -H "authorization: Bearer ${GH_TOKEN}" \
+          --data "$comment_json" \
+          --fail
